[package]
name = "d16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-lib = { version = "0.1.0", path = "../../advent-lib" }
tap = "1.0.1"
